In [1]:
import numpy as np

# How to create a 3d 3dimentional numpy array in python

In [2]:
n=np.array([[[1,2,3],[4,5,6]],
            [[7,8,9],[10,11,12]]])

In [3]:
print ("Our 3D array...\n",n)
print("\nArray Type...\n",type(n))
print("\nShape of Array...\n",n.shape)


Our 3D array...
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Array Type...
 <class 'numpy.ndarray'>

Shape of Array...
 (2, 2, 3)


In [4]:
import numpy as np

In [5]:
A=np.array([
    [2,-3,1],
    [2,0,-1],
    [1,4,5]
])

In [6]:
A

array([[ 2, -3,  1],
       [ 2,  0, -1],
       [ 1,  4,  5]])

# A 3D array is a bunch of two 2D arrays [2(2*3)]
# A 3D array is a multi-dimensional array(array of arrays). 
# A 3D array is a collection of 2D arrays . 
# It is specified by using three subscripts:Block size, row size and column size. More dimensions in an array means more data can be stored in that array.

# 3-D arrays are referred to as multi-dimensional arrays. 
# Multi-dimensional arrays are defined as an “array of arrays” that store data in a tabular form.

# 3D array

In [7]:
B=np.array([
    [[1,2,3],
    [4,5,6]],
    
    [[7,8,9],
    [10,11,12]]
])

print(B.shape)

(2, 2, 3)


In [8]:
print(B.ndim)

3


# 1 - D array

In [9]:
import numpy as np

In [10]:
a=np.array([1,2,3,4,5])
b=np.array((1,2,3,4,5))
print(a)
print(b)

[1 2 3 4 5]
[1 2 3 4 5]


# 2-D array

### 2D array created using tuple function

In [11]:
a2=np.array([(1,2,3),(2,3,4)])
a2

array([[1, 2, 3],
       [2, 3, 4]])

### 2D array created using a list function

In [12]:
b2=np.array([[1,2,3],[2,3,4]])
b2

array([[1, 2, 3],
       [2, 3, 4]])

### Dimension

In [13]:
a2.ndim

2

In [14]:
a.ndim

1

## How to create a 3D array

#### 2D =arr[3][3]
#### 3D =arr[2][3][3]

In [15]:
a3=np.array([((1,2,3),(2,3,4)),((1,2,3),(3,4,5)) ])
a3

array([[[1, 2, 3],
        [2, 3, 4]],

       [[1, 2, 3],
        [3, 4, 5]]])

In [16]:
a3.ndim

3

# Accessing array elements

In [17]:
a3[1][1][2]

5

In [18]:
a2

array([[1, 2, 3],
       [2, 3, 4]])

In [19]:
a2[1][1]

3

# Changing Array Elements

In [20]:
a2[1][1]=23

In [21]:
a2

array([[ 1,  2,  3],
       [ 2, 23,  4]])

In [22]:
a3

array([[[1, 2, 3],
        [2, 3, 4]],

       [[1, 2, 3],
        [3, 4, 5]]])

In [23]:
a3[1][0][1]=25

In [24]:
a3

array([[[ 1,  2,  3],
        [ 2,  3,  4]],

       [[ 1, 25,  3],
        [ 3,  4,  5]]])

# Initialize different types of array

In [25]:
a=np.zeros((2,3),dtype='int32')

In [26]:
a

array([[0, 0, 0],
       [0, 0, 0]])

In [27]:
np.ones((3,3),dtype='int32')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [28]:
np.full((3,3),99)

array([[99, 99, 99],
       [99, 99, 99],
       [99, 99, 99]])

In [29]:
# Create an identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
a=np.arange(1,31)

In [31]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [32]:
a.reshape(5,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [36]:
np.ones((4,5),dtype='int32')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# numpy array takes lesser memory
# numpy array is good for mathematical computation.
# hetrogenous list can be made in numpy array

In [1]:
import numpy as np

In [6]:
x=np.array([1,'Hi',True])

In [7]:
x

array(['1', 'Hi', 'True'], dtype='<U11')

In [4]:
x[0]

'1'

In [5]:
x[2]

'True'

In [8]:
x[2] is True

False

In [11]:
x[2]=True

In [12]:
x

array(['1', 'Hi', 'True'], dtype='<U11')

In [ ]:
x=