In [ ]:
* numpy = numerical python 
# 
# * numerical python use  built using 'c' language.
# 
# * Because it code in 'c' to address a specific purpose.
# 
# *Numerical computation in numpy in 'c' code.
# 
# *it is faster when compared to python list(nested list)
# 
# *In numpy we have multi-dimentional array
#  
#  
#  Note----> numpy arrys are not only faster than python's list,
#  
#  but they also offer convinence & functionality .
#  
#  with respective numarical cometions like vector & matric's operations.
#  
#  scince numpy is coded in 'c' & 'c' loops  would requred type chats,
#  
#  over python APL book keeping
#  
#  couple of oprtion's can be
#  
#  careed out more effctivly
#  
#  Numpy arrys as fixed lenth, updateing 
#  
#  numpy arry we will create new numppy arry & deleate
#  
#  previous one.
#  
#  *numpy arry also  consumes less memory

In [1]:
import numpy as np

In [2]:
oneD = np.array([1,2,3,4,5])
oneD

array([1, 2, 3, 4, 5])

In [7]:
type(oneD)

numpy.ndarray

In [4]:
# dir(oneD)

In [30]:
print(oneD)
print(f'''The oneD array belongs to type{type(oneD)} of {oneD.ndim} dimenstion,
    has lenght {len(oneD)} , with size {oneD.size} and shape {oneD.shape} ''')

[1 2 3 4 5]
The oneD array belongs to type<class 'numpy.ndarray'> of 1 dimenstion,
    has lenght 5 , with size 5 and shape (5,) 


In [14]:
# creating a 2-d array

In [27]:
twoD = np.array([[1,2,3],
                 [4,5,6]])
print(twoD)
print(f'''The oneD array belongs to type{type(twoD)} of {twoD.ndim} dimenstion, 
    has lenght {len(twoD)} , with size {twoD.size} and shape {twoD.shape} ''')

[[1 2 3]
 [4 5 6]]
The oneD array belongs to type<class 'numpy.ndarray'> of 2 dimenstion, 
    has lenght 2 , with size 6 and shape (2, 3) 


In [14]:
threeD = np.array([[[1,2,3],
                    [4,5,6],
                    [7,8,9]]])
print(threeD)
print(f'''The oneD array belongs to type{type(threeD)} of {threeD.ndim} dimenstion, 
    has lenght {len(threeD)} , with size {threeD.size} and shape {threeD.shape} ''')

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
The oneD array belongs to type<class 'numpy.ndarray'> of 3 dimenstion, 
    has lenght 1 , with size 9 and shape (1, 3, 3) 


In [70]:
threeD = np.array([[[1,2,3],
                    [4,5,6]],
                    
                    [[7,8,9],
                    [10,11,12]]])
print(threeD)
print(f'''The oneD array belongs to type{type(threeD)} of {threeD.ndim} dimenstion, 
    has lenght {len(threeD)} , with size {threeD.size} and shape {threeD.shape} ''')

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
The oneD array belongs to type<class 'numpy.ndarray'> of 3 dimenstion, 
    has lenght 2 , with size 12 and shape (2, 2, 3) 


In [71]:
x = [1,2,3,4,5,
      [6,7,8,9,
        [10,11,12,
           [13,14,
             [15]]]]]


x = np.array(x)
x

C:\Users\kalag\AppData\Local\Temp\ipykernel_14944\391596526.py:8: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  x = np.array(x)


array([1, 2, 3, 4, 5, list([6, 7, 8, 9, [10, 11, 12, [13, 14, [15]]]])],
      dtype=object)

In [72]:
print(f'''The oneD array belongs to type{type(x)} of {x.ndim} dimenstion, 
    has lenght {len(x)} , with size {x.size} and shape {x.shape} ''')

The oneD array belongs to type<class 'numpy.ndarray'> of 1 dimenstion, 
    has lenght 6 , with size 6 and shape (6,) 


In [73]:
a= list([6, 7, [10, 11, [13, 14]]])
a

[6, 7, [10, 11, [13, 14]]]

In [74]:
x = [6, 7, [10, 11, [13, 14]]]
x = np.array(x)
x

C:\Users\kalag\AppData\Local\Temp\ipykernel_14944\1049661893.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  x = np.array(x)


array([6, 7, list([10, 11, [13, 14]])], dtype=object)

In [46]:
print(f'''The oneD array belongs to type{type(x)} of {x.ndim} dimenstion, 
    has lenght {len(x)} , with size {x.size} and shape {x.shape} ''')

The oneD array belongs to type<class 'numpy.ndarray'> of 1 dimenstion, 
    has lenght 3 , with size 3 and shape (3,) 


In [47]:
# indexing & slicing

In [58]:
print(twoD)
twoD[0] , twoD[0][0] , twoD[0,0]

[[1 2 3]
 [4 5 6]]


(array([1, 2, 3]), 1, 1)

In [61]:
oneD = np.array([ele for ele in range(1,21)])
print(oneD)
oneD[::]

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [63]:
oneD[::-1]

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
        3,  2,  1])

In [66]:
oneD[2:10:2] , oneD[-2:-10:-2]

(array([3, 5, 7, 9]), array([19, 17, 15, 13]))

In [67]:
oneD[20:10:-1]

array([20, 19, 18, 17, 16, 15, 14, 13, 12])

In [69]:
oneD[-1:-9:-1]

array([20, 19, 18, 17, 16, 15, 14, 13])

In [5]:
threeD = np.array([[[1,2,3],
                    [4,5,6]],
                    
                    [[7,8,9],
                    [10,11,12]],
                    
                    [[13,14,15],
                    [16,17,18]]])
print(threeD)
print(f'''The oneD array belongs to type{type(threeD)} of {threeD.ndim} dimenstion, 
    has lenght {len(threeD)} , with size {threeD.size} and shape {threeD.shape} ''')threeD = np.array([[[1,2,3],
                    [4,5,6]],
                    
                    [[7,8,9],
                    [10,11,12]],
                    
                    [[13,14,15],
                    [16,17,18]]])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
The oneD array belongs to type<class 'numpy.ndarray'> of 3 dimenstion, 
    has lenght 3 , with size 18 and shape (3, 2, 3) 


In [11]:
threeD[1,1,1]

11

In [7]:
threeD[1][:][::2]

array([[7, 8, 9]])

In [8]:
threeD[1,:,::2]

array([[ 7,  9],
       [10, 12]])

In [9]:
threeD[1][:][::2]

array([[7, 8, 9]])

In [22]:
help(str.strip)

Help on method_descriptor:

strip(self, chars=None, /)
    Return a copy of the string with leading and trailing whitespace removed.
    
    If chars is given and not None, remove characters in chars instead.



In [4]:
import numpy as np

In [5]:
threeD = np.array([[[1,2,3],
                    [4,5,6]],
                    
                    [[7,8,9],
                    [10,11,12]],
                    
                    [[13,14,15],
                    [16,17,18]]])

In [6]:
threeD[1][1,1]

11

In [7]:
threeD[2][0][1]

14

In [9]:
threeD[[::2]

array([[1, 2, 3]])

In [11]:
threeD[0::2,:,::2]

array([[[ 1,  3],
        [ 4,  6]],

       [[13, 15],
        [16, 18]]])

In [12]:
threeD[::2]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [13]:
threeD[-1]

array([[13, 14, 15],
       [16, 17, 18]])

In [24]:
threeD[::-1,0,:2]

array([[13, 14],
       [ 7,  8],
       [ 1,  2]])

# numpy Dtypes stands for data types and it describes how the bites of numpy array should be interpreted as.


# It also describes whether a data type a sub array and its shape. It also describes the size of the data
# Lesser than a symbol in the beginning of dtype it means it is encoded in little endian encoding the least 
# Most significant value is stored in the smallest address.
# 

# Available dtypes in numpy

# numpy array in list

In [25]:
import sys

In [26]:
import time

In [29]:
a=np.arange(1,10)

In [30]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
import numpy as np

In [3]:
x=np.arange(45,60)

In [4]:
x

array([45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [6]:
# help(np.arange)

In [20]:
# np.arrays vs lists

import sys, time


In [29]:
start=time.time()
xls=[i for i in range(1,1000001)]
end=time.time()
tls=end-start

In [33]:
start=time.time()
xnp=np.arange(1,1000001)
end=time.time()
tnp=end-start


In [34]:
tls,tnp

(0.0812063217163086, 0.0)

In [35]:
sys.getsizeof(xls), sys.getsizeof(xnp)

(8448728, 4000112)

In [37]:
sys.getsizeof(xls[-1]), xnp.itemsize

(28, 4)

# element wise operations

In [38]:
xls=[1,2,3]
xnp=np.array(xls)
xls, xnp

([1, 2, 3], array([1, 2, 3]))

In [39]:
xnp + 3

array([4, 5, 6])

In [41]:
xls + 3

TypeError: can only concatenate list (not "int") to list

In [42]:
xx = xls + xnp

In [43]:
xx

array([2, 4, 6])

In [45]:
type(xx),xx

(numpy.ndarray, array([2, 4, 6]))

In [47]:
def foo(x):
    return x**0.5

In [48]:
foo(xnp)

array([1.        , 1.41421356, 1.73205081])

# dtype

In [49]:
a = np.arange(1,11, dtype='float64')

In [50]:
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

# ndmin

In [58]:
a=np.array([[1,2,3],[4,5,6]],ndmin=5)

In [59]:
a

array([[[[[1, 2, 3],
          [4, 5, 6]]]]])

# ones in numpy array

In [60]:
import numpy as np

In [70]:

x=np.ones(5)
y=np.ones((3,3))
z=np.ones((3,3,3))

print(x,y,z, sep='\n\n')

[1. 1. 1. 1. 1.]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [71]:

x=np.zeros(5)
y=np.zeros((3,3))
z=np.zeros((3,3,3))

print(x,y,z, sep='\n\n')

[0. 0. 0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


# identity matrix

In [72]:
x=np.eye(2)
y=np.eye(3)
z=np.eye(4)

print(x,y,z, sep='\n\n')

[[1. 0.]
 [0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# linspace

In [73]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

In [74]:
np.linspace(0,100)

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [75]:
np.linspace(1,100,10, dtype='int16')


array([  1,  12,  23,  34,  45,  56,  67,  78,  89, 100], dtype=int16)

In [76]:
np.linspace(0,100,10, dtype='int16')


array([  0,  11,  22,  33,  44,  55,  66,  77,  88, 100], dtype=int16)

In [77]:
len(np.linspace(0,100))

50

# Random

In [79]:
# help(np.random)

In [83]:
np.random.seed(225)
np.random.randint(1,100)

36

In [87]:
np.random.seed(420)
np.random.randint(1,100)

50

In [ ]:
a = np.r


In [88]:
import random

random.seed(10)
print(random.random())

0.5714025946899135


In [94]:
a=np.random.randint(1,100,9)
b=np.random.randint(1,100,(3,3))
c=np.random.randint(1,100,(3,3,3))
print(a,b,c, sep='\n\n')

[13 92 10 28 61 55 56 14 27]

[[71 90 41]
 [17 62 47]
 [32 72 78]]

[[[94 51 90]
  [ 3 23 47]
  [47 80 53]]

 [[46 16 55]
  [55 75 41]
  [12 11 15]]

 [[90 69 48]
  [14 61 41]
  [ 2 69 86]]]


In [98]:
# reshape

a=np.random.randint(1,100,36)
print(a, a.shape)

[75 63 33  2 28 18  5 75 94 38 18 82 89 23 68 63  7 55 24 56  3 63  3 67
 74 31 90 36 69  4 31 36 44 73 19 44] (36,)


In [100]:
a.reshape(1,36) # one row and 36 columns

array([[75, 63, 33,  2, 28, 18,  5, 75, 94, 38, 18, 82, 89, 23, 68, 63,
         7, 55, 24, 56,  3, 63,  3, 67, 74, 31, 90, 36, 69,  4, 31, 36,
        44, 73, 19, 44]])

In [101]:
a.reshape(6,6)

array([[75, 63, 33,  2, 28, 18],
       [ 5, 75, 94, 38, 18, 82],
       [89, 23, 68, 63,  7, 55],
       [24, 56,  3, 63,  3, 67],
       [74, 31, 90, 36, 69,  4],
       [31, 36, 44, 73, 19, 44]])

In [103]:
a.reshape(6,2,3)

array([[[75, 63, 33],
        [ 2, 28, 18]],

       [[ 5, 75, 94],
        [38, 18, 82]],

       [[89, 23, 68],
        [63,  7, 55]],

       [[24, 56,  3],
        [63,  3, 67]],

       [[74, 31, 90],
        [36, 69,  4]],

       [[31, 36, 44],
        [73, 19, 44]]])

In [104]:
a.reshape(3,2,6)

array([[[75, 63, 33,  2, 28, 18],
        [ 5, 75, 94, 38, 18, 82]],

       [[89, 23, 68, 63,  7, 55],
        [24, 56,  3, 63,  3, 67]],

       [[74, 31, 90, 36, 69,  4],
        [31, 36, 44, 73, 19, 44]]])

In [105]:
a.reshape(3,2,3,2)

array([[[[75, 63],
         [33,  2],
         [28, 18]],

        [[ 5, 75],
         [94, 38],
         [18, 82]]],


       [[[89, 23],
         [68, 63],
         [ 7, 55]],

        [[24, 56],
         [ 3, 63],
         [ 3, 67]]],


       [[[74, 31],
         [90, 36],
         [69,  4]],

        [[31, 36],
         [44, 73],
         [19, 44]]]])

# flatten and ravel

In [15]:
a=np.random.randint(1,11,(3,3))
a

array([[ 3,  7,  5],
       [10,  6,  2],
       [ 3,  3,  9]])

In [16]:
a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
aRavel=a.ravel()
aFlatten = a.flatten()

In [18]:
print(aRavel, aFlatten, sep = '\n\n')

[1 2 3 4 5 6 7 8 9]

[1 2 3 4 5 6 7 8 9]


In [19]:
a[1,1]

5

In [20]:
a[1,1]=50

In [21]:
a

array([[ 1,  2,  3],
       [ 4, 50,  6],
       [ 7,  8,  9]])

In [22]:
print(aRavel, aFlatten, sep = '\n\n')

[ 1  2  3  4 50  6  7  8  9]

[1 2 3 4 5 6 7 8 9]


# Ravel is a shallow copy and Flatten is a deep copy
# Flatten always produces a one-dimensional copy, 
# whereas ravel attempts to provide a one-dimensional view of the original matrix.
# Be cautious since altering the returned matrix from ravel may make changes to the original matrix. 
# Modifying the content of the array created by flatten has no effect on the original array.


In [23]:
print(id(a[0]), id(aRavel[0]), id(aFlatten[0]))

2427438538096 2427437854384 2427437854384


In [24]:
print(id(a[1,1]), id(aRavel[4]), id(aFlatten[4]))

2427437852688 2427437852688 2427437852688


In [25]:
aFlatten[4]

5

In [26]:
aRavel[4]

50

# numpy is numerical python

In [27]:
import numpy as np

In [28]:
# ravel is a shallow copy and flatten is a deep copy

In [29]:
# aRavel[4]

In [30]:
# aFlatten[4]

In [31]:
# sort

x =np.random.randint(1,50,(5,5))

In [32]:
x

array([[15,  9, 16, 19,  1],
       [24, 25,  2, 28,  7],
       [36, 31,  8, 18, 28],
       [29, 26, 31, 34,  8],
       [22, 29, 48, 23, 38]])

In [33]:
np.sort(aRavel)

array([ 1,  2,  3,  4,  6,  7,  8,  9, 50])

In [34]:
aRavel

array([ 1,  2,  3,  4, 50,  6,  7,  8,  9])

In [38]:
# help(np.sort)

In [39]:
np.sort(x)  # Row wise sorting

array([[ 1,  9, 15, 16, 19],
       [ 2,  7, 24, 25, 28],
       [ 8, 18, 28, 31, 36],
       [ 8, 26, 29, 31, 34],
       [22, 23, 29, 38, 48]])

In [40]:
np.sort(x, axis=1) # columns wise sorting

array([[ 1,  9, 15, 16, 19],
       [ 2,  7, 24, 25, 28],
       [ 8, 18, 28, 31, 36],
       [ 8, 26, 29, 31, 34],
       [22, 23, 29, 38, 48]])

In [41]:
y = np.random.randint(0,100,(3,3,3))

In [42]:
y

array([[[81, 23, 26],
        [44, 78, 68],
        [89, 73, 39]],

       [[35, 29, 15],
        [67, 85, 78],
        [21, 91, 17]],

       [[79, 48, 21],
        [63, 15, 53],
        [47, 68, 32]]])

In [43]:
np.sort(y) # if no axis is provided, the sorting happens on row-wise

array([[[23, 26, 81],
        [44, 68, 78],
        [39, 73, 89]],

       [[15, 29, 35],
        [67, 78, 85],
        [17, 21, 91]],

       [[21, 48, 79],
        [15, 53, 63],
        [32, 47, 68]]])

In [45]:
np.sort(y, axis=1) # 0=row wise, 1=column wise

array([[[44, 23, 26],
        [81, 73, 39],
        [89, 78, 68]],

       [[21, 29, 15],
        [35, 85, 17],
        [67, 91, 78]],

       [[47, 15, 21],
        [63, 48, 32],
        [79, 68, 53]]])

In [46]:
np.sort(y, axis=2) # 0=row wise, 1=column wise

array([[[23, 26, 81],
        [44, 68, 78],
        [39, 73, 89]],

       [[15, 29, 35],
        [67, 78, 85],
        [17, 21, 91]],

       [[21, 48, 79],
        [15, 53, 63],
        [32, 47, 68]]])

In [49]:
y

array([[[81, 23, 26],
        [44, 78, 68],
        [89, 73, 39]],

       [[35, 29, 15],
        [67, 85, 78],
        [21, 91, 17]],

       [[79, 48, 21],
        [63, 15, 53],
        [47, 68, 32]]])

In [48]:
np.sort(y, axis=-1)

array([[[23, 26, 81],
        [44, 68, 78],
        [39, 73, 89]],

       [[15, 29, 35],
        [67, 78, 85],
        [17, 21, 91]],

       [[21, 48, 79],
        [15, 53, 63],
        [32, 47, 68]]])

In [50]:
aRavel

array([ 1,  2,  3,  4, 50,  6,  7,  8,  9])

In [52]:
np.argmin(aRavel)

0

In [53]:
np.argmin(aRavel),np.argmax(aRavel)

(0, 4)

In [54]:
print(aRavel)

[ 1  2  3  4 50  6  7  8  9]


In [56]:
print(x)
np.argmin(aRavel),np.argmax(aRavel)

[[15  9 16 19  1]
 [24 25  2 28  7]
 [36 31  8 18 28]
 [29 26 31 34  8]
 [22 29 48 23 38]]


(0, 4)

In [68]:
print(y,'\n')
print(np.argmin(y),np.argmax(y)) # row wise
print(np.argmin(y, axis=1), np.argmax(y, axis=1), sep='****\n') 
print(np.argmin(y, axis=0), np.argmax(y, axis=0), sep='****\n') 

[[[81 23 26]
  [44 78 68]
  [89 73 39]]

 [[35 29 15]
  [67 85 78]
  [21 91 17]]

 [[79 48 21]
  [63 15 53]
  [47 68 32]]] 

11 16
[[1 0 0]
 [2 0 0]
 [2 1 0]]****
[[2 1 1]
 [1 2 1]
 [0 2 1]]
[[1 0 1]
 [0 2 2]
 [1 2 1]]****
[[0 2 0]
 [1 1 1]
 [0 1 0]]


In [69]:
#expand squueze

aRavel

array([ 1,  2,  3,  4, 50,  6,  7,  8,  9])

In [70]:
np.expand_dims(aRavel, axis=0)

array([[ 1,  2,  3,  4, 50,  6,  7,  8,  9]])

In [71]:
np.expand_dims(aRavel, axis=1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [50],
       [ 6],
       [ 7],
       [ 8],
       [ 9]])

In [72]:
np.expand_dims(aRavel, axis=0)

array([[ 1,  2,  3,  4, 50,  6,  7,  8,  9]])

In [78]:
np.expand_dims(aRavel, axis=1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [50],
       [ 6],
       [ 7],
       [ 8],
       [ 9]])

In [86]:
np.expand_dims(y, axis=2)

array([[[[81, 23, 26]],

        [[44, 78, 68]],

        [[89, 73, 39]]],


       [[[35, 29, 15]],

        [[67, 85, 78]],

        [[21, 91, 17]]],


       [[[79, 48, 21]],

        [[63, 15, 53]],

        [[47, 68, 32]]]])

In [81]:
z=np.expand_dims(x, axis=1)

In [82]:
z

array([[[15,  9, 16, 19,  1]],

       [[24, 25,  2, 28,  7]],

       [[36, 31,  8, 18, 28]],

       [[29, 26, 31, 34,  8]],

       [[22, 29, 48, 23, 38]]])

In [84]:
np.squeeze(z, axis=1)

array([[15,  9, 16, 19,  1],
       [24, 25,  2, 28,  7],
       [36, 31,  8, 18, 28],
       [29, 26, 31, 34,  8],
       [22, 29, 48, 23, 38]])

In [89]:
d=np.array([[1],[2]])
d

array([[1],
       [2]])

In [90]:
np.squeeze(d,axis=1)

array([1, 2])